title = "Nicolas Crausaz"
baseURL = "https://crausaz.click/"
theme = "ncrausaz"
defaultContentLanguage = "fr"
hasCJKLanguage = false
defaultContentLanguageInSubdir = false

[params]
  author = "Nicolas Crausaz"

[languages]
  [languages.fr]
    languageCode = "fr"
    languageName = "Français"
    weight = 1
    [languages.fr.params]
      description = "Nicolas Crausaz, ingénieur en informatique logicielle"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    [languages.en.params]
      description = "Nicolas Crausaz, Software Engineer"

[taxonomies]

[services]
  [services.googleAnalytics]
    ID = 'G-7GV42PYC7G'

[sitemap]
  changeFreq = 'monthly'
  filename = 'sitemap.xml'
  priority = -1
