title = "Nicolas Crausaz"
baseURL = "https://crausaz.click/"
theme = "ncrausaz"
sitemap = "sitemap.xml"
defaultContentLanguage = "fr"
hasCJKLanguage = false 
defaultContentLanguageInSubdir = false
[taxonomies]

[services]
  [services.googleAnalytics]
    ID = 'G-7GV42PYC7G'
